package com.autobot.rpa.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF1976D2)
val PrimaryVariant = Color(0xFF1565C0)
val Secondary = Color(0xFF4CAF50)
val SecondaryVariant = Color(0xFF388E3C)
val Background = Color(0xFFFAFAFA)
val Surface = Color(0xFFFFFFFF)
val Error = Color(0xFFF44336)
val Warning = Color(0xFFFF9800)
val OnPrimary = Color(0xFFFFFFFF)
val OnSecondary = Color(0xFFFFFFFF)
val OnBackground = Color(0xFF212121)
val OnSurface = Color(0xFF212121)
val OnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFF1E88E5)
val DarkPrimaryVariant = Color(0xFF1565C0)
val DarkSecondary = Color(0xFF66BB6A)
val DarkSecondaryVariant = Color(0xFF388E3C)
val DarkBackground = Color(0xFF121212)
val DarkSurface = Color(0xFF1E1E1E)
val DarkError = Color(0xFFEF5350)
val DarkWarning = Color(0xFFFFB74D)
val DarkOnPrimary = Color(0xFFFFFFFF)
val DarkOnSecondary = Color(0xFFFFFFFF)
val DarkOnBackground = Color(0xFFE0E0E0)
val DarkOnSurface = Color(0xFFE0E0E0)
val DarkOnError = Color(0xFFFFFFFF)
